image:
  file: .gitpod.Dockerfile
ports:
  - port: 8787
    onOpen: open-preview
tasks:
  - command: /usr/lib/rstudio-server/bin/rserver --auth-none 1 --server-user gitpod
vscode:
  extensions:
  - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
